/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swingkavir;

/**
 *
 * @author kaavi
 */
public class QuestionFrame4 extends javax.swing.JFrame implements QuestionInterface{

    /**
     * Creates new form QuestionFrame4
     */
    public QuestionFrame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioAnswers2 = new javax.swing.ButtonGroup();
        Question4 = new javax.swing.JPanel();
        answerProgressBar = new javax.swing.JProgressBar();
        questionSetPanel7 = new javax.swing.JPanel();
        questionPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        answersPanel7 = new javax.swing.JPanel();
        radioAnswer2 = new javax.swing.JRadioButton();
        radioAnswer3 = new javax.swing.JRadioButton();
        radioAnswer4 = new javax.swing.JRadioButton();
        radioAnswer1 = new javax.swing.JRadioButton();
        radioAnswer5 = new javax.swing.JRadioButton();
        radioAnswer6 = new javax.swing.JRadioButton();
        radioAnswer7 = new javax.swing.JRadioButton();
        radioAnswer8 = new javax.swing.JRadioButton();
        buttonNext = new javax.swing.JButton();
        buttonPrevious = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 250));

        Question4.setBackground(new java.awt.Color(108, 145, 191));
        Question4.setMaximumSize(new java.awt.Dimension(1000, 800));
        Question4.setMinimumSize(new java.awt.Dimension(1000, 800));

        questionSetPanel7.setBackground(new java.awt.Color(95, 154, 183));
        questionSetPanel7.setMaximumSize(new java.awt.Dimension(800, 500));
        questionSetPanel7.setMinimumSize(new java.awt.Dimension(800, 500));

        questionPanel7.setBackground(new java.awt.Color(95, 176, 183));
        questionPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel15.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Select the pillars of OOP");

        javax.swing.GroupLayout questionPanel7Layout = new javax.swing.GroupLayout(questionPanel7);
        questionPanel7.setLayout(questionPanel7Layout);
        questionPanel7Layout.setHorizontalGroup(
            questionPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel7Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        questionPanel7Layout.setVerticalGroup(
            questionPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        answersPanel7.setBackground(new java.awt.Color(95, 176, 183));
        answersPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        radioAnswer2.setText("Encapsulation");
        radioAnswer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer2MouseClicked(evt);
            }
        });

        radioAnswer3.setText("Polymorphism");
        radioAnswer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer3MouseClicked(evt);
            }
        });

        radioAnswer4.setText("Clean code");
        radioAnswer4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer4MouseClicked(evt);
            }
        });

        radioAnswer1.setText("Sharing");
        radioAnswer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer1MouseClicked(evt);
            }
        });

        radioAnswer5.setText("Inheritance");
        radioAnswer5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer5MouseClicked(evt);
            }
        });

        radioAnswer6.setText("Escalability");
        radioAnswer6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer6MouseClicked(evt);
            }
        });

        radioAnswer7.setText("Privacy");
        radioAnswer7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer7MouseClicked(evt);
            }
        });

        radioAnswer8.setText("Abstraction");
        radioAnswer8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout answersPanel7Layout = new javax.swing.GroupLayout(answersPanel7);
        answersPanel7.setLayout(answersPanel7Layout);
        answersPanel7Layout.setHorizontalGroup(
            answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answersPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(answersPanel7Layout.createSequentialGroup()
                        .addGroup(answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioAnswer3)
                            .addComponent(radioAnswer4))
                        .addGap(22, 22, 22)
                        .addGroup(answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioAnswer8)
                            .addComponent(radioAnswer7)))
                    .addGroup(answersPanel7Layout.createSequentialGroup()
                        .addGroup(answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answersPanel7Layout.createSequentialGroup()
                                .addComponent(radioAnswer2)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answersPanel7Layout.createSequentialGroup()
                                .addComponent(radioAnswer1)
                                .addGap(59, 59, 59)))
                        .addGroup(answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioAnswer5)
                            .addComponent(radioAnswer6))
                        .addGap(3, 3, 3)))
                .addGap(294, 294, 294))
        );
        answersPanel7Layout.setVerticalGroup(
            answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answersPanel7Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAnswer1)
                    .addComponent(radioAnswer5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAnswer2)
                    .addComponent(radioAnswer6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAnswer3)
                    .addComponent(radioAnswer7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(answersPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAnswer4)
                    .addComponent(radioAnswer8))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout questionSetPanel7Layout = new javax.swing.GroupLayout(questionSetPanel7);
        questionSetPanel7.setLayout(questionSetPanel7Layout);
        questionSetPanel7Layout.setHorizontalGroup(
            questionSetPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSetPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(questionSetPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(questionPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answersPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        questionSetPanel7Layout.setVerticalGroup(
            questionSetPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSetPanel7Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(questionPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(answersPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        buttonNext.setBackground(new java.awt.Color(95, 176, 183));
        buttonNext.setText("Next");
        buttonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNextMouseClicked(evt);
            }
        });

        buttonPrevious.setBackground(new java.awt.Color(95, 176, 183));
        buttonPrevious.setText("Previous");
        buttonPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPreviousMouseClicked(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(95, 154, 183));
        jLabel16.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Java Evaluation");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setOpaque(true);

        javax.swing.GroupLayout Question4Layout = new javax.swing.GroupLayout(Question4);
        Question4.setLayout(Question4Layout);
        Question4Layout.setHorizontalGroup(
            Question4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(answerProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Question4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question4Layout.createSequentialGroup()
                        .addGroup(Question4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Question4Layout.createSequentialGroup()
                                .addComponent(buttonPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(questionSetPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );
        Question4Layout.setVerticalGroup(
            Question4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(questionSetPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Question4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonNext, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(buttonPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(answerProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Question4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Question4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPreviousMouseClicked
        // TODO add your handling code here:
        FormController.goPrevious(4);
    }//GEN-LAST:event_buttonPreviousMouseClicked

    private void buttonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNextMouseClicked
        // TODO add your handling code here:
        FormController.goNext(4);
    }//GEN-LAST:event_buttonNextMouseClicked

    private void radioAnswer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer1MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(4,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer1MouseClicked

    private void radioAnswer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer2MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(4,"radio", evt.getSource());

    }//GEN-LAST:event_radioAnswer2MouseClicked

    private void radioAnswer3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer3MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(4,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer3MouseClicked

    private void radioAnswer4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer4MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(4,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer4MouseClicked

    private void radioAnswer5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer5MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(4,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer5MouseClicked

    private void radioAnswer6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer6MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(4,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer6MouseClicked

    private void radioAnswer7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer7MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(4,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer7MouseClicked

    private void radioAnswer8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer8MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(4,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer8MouseClicked
    
    @Override
    public void updateProgressBar(int progress) {
        answerProgressBar.setValue(progress);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Question4;
    private javax.swing.JProgressBar answerProgressBar;
    private javax.swing.JPanel answersPanel7;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonPrevious;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel questionPanel7;
    private javax.swing.JPanel questionSetPanel7;
    private javax.swing.JRadioButton radioAnswer1;
    private javax.swing.JRadioButton radioAnswer2;
    private javax.swing.JRadioButton radioAnswer3;
    private javax.swing.JRadioButton radioAnswer4;
    private javax.swing.JRadioButton radioAnswer5;
    private javax.swing.JRadioButton radioAnswer6;
    private javax.swing.JRadioButton radioAnswer7;
    private javax.swing.JRadioButton radioAnswer8;
    private javax.swing.ButtonGroup radioAnswers2;
    // End of variables declaration//GEN-END:variables
}
