/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swingkavir;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JRadioButton;

/**
 *
 * @author kaavi
 */
public class QuestionFrame0 extends javax.swing.JFrame implements QuestionInterface{

    /**
     * Creates new form FormFrame
     */
    public QuestionFrame0() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Question0 = new javax.swing.JPanel();
        answerProgressBar = new javax.swing.JProgressBar();
        questionSetPanel = new javax.swing.JPanel();
        questionPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        answersPanel = new javax.swing.JPanel();
        answer2 = new javax.swing.JRadioButton();
        answer3 = new javax.swing.JRadioButton();
        answer4 = new javax.swing.JRadioButton();
        answer1 = new javax.swing.JRadioButton();
        answer5 = new javax.swing.JRadioButton();
        answer6 = new javax.swing.JRadioButton();
        answer7 = new javax.swing.JRadioButton();
        answer8 = new javax.swing.JRadioButton();
        buttonNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 250));
        setResizable(false);

        Question0.setBackground(new java.awt.Color(108, 145, 191));
        Question0.setMaximumSize(new java.awt.Dimension(1000, 800));
        Question0.setMinimumSize(new java.awt.Dimension(1000, 800));
        Question0.setPreferredSize(new java.awt.Dimension(1000, 800));

        questionSetPanel.setBackground(new java.awt.Color(95, 154, 183));
        questionSetPanel.setMaximumSize(new java.awt.Dimension(800, 500));
        questionSetPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        questionSetPanel.setPreferredSize(new java.awt.Dimension(800, 500));

        questionPanel.setBackground(new java.awt.Color(95, 176, 183));
        questionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select valid Java primitive types");

        javax.swing.GroupLayout questionPanelLayout = new javax.swing.GroupLayout(questionPanel);
        questionPanel.setLayout(questionPanelLayout);
        questionPanelLayout.setHorizontalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        questionPanelLayout.setVerticalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        answersPanel.setBackground(new java.awt.Color(95, 176, 183));
        answersPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        answer2.setText("jar");
        answer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer2MouseClicked(evt);
            }
        });

        answer3.setText("int");
        answer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer3MouseClicked(evt);
            }
        });

        answer4.setText("img");
        answer4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer4MouseClicked(evt);
            }
        });

        answer1.setText("Vector");
        answer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer1MouseClicked(evt);
            }
        });

        answer5.setText("float");
        answer5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer5MouseClicked(evt);
            }
        });

        answer6.setText("long");
        answer6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer6MouseClicked(evt);
            }
        });

        answer7.setText("ArrayList");
        answer7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer7MouseClicked(evt);
            }
        });

        answer8.setText("double");
        answer8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout answersPanelLayout = new javax.swing.GroupLayout(answersPanel);
        answersPanel.setLayout(answersPanelLayout);
        answersPanelLayout.setHorizontalGroup(
            answersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answersPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addGroup(answersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(answersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answersPanelLayout.createSequentialGroup()
                            .addComponent(answer2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answer6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answersPanelLayout.createSequentialGroup()
                            .addComponent(answer1)
                            .addGap(44, 44, 44)
                            .addComponent(answer5)))
                    .addGroup(answersPanelLayout.createSequentialGroup()
                        .addComponent(answer3)
                        .addGap(64, 64, 64)
                        .addComponent(answer7))
                    .addGroup(answersPanelLayout.createSequentialGroup()
                        .addComponent(answer4)
                        .addGap(57, 57, 57)
                        .addComponent(answer8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        answersPanelLayout.setVerticalGroup(
            answersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answersPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(answersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer1)
                    .addComponent(answer5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(answersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer6)
                    .addComponent(answer2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(answersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer7)
                    .addComponent(answer3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(answersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer8)
                    .addComponent(answer4))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout questionSetPanelLayout = new javax.swing.GroupLayout(questionSetPanel);
        questionSetPanel.setLayout(questionSetPanelLayout);
        questionSetPanelLayout.setHorizontalGroup(
            questionSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSetPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(questionSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(questionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        questionSetPanelLayout.setVerticalGroup(
            questionSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSetPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(questionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(answersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        buttonNext.setBackground(new java.awt.Color(95, 176, 183));
        buttonNext.setText("Next");
        buttonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNextMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(95, 154, 183));
        jLabel1.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Java Evaluation");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout Question0Layout = new javax.swing.GroupLayout(Question0);
        Question0.setLayout(Question0Layout);
        Question0Layout.setHorizontalGroup(
            Question0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(answerProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question0Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Question0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question0Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question0Layout.createSequentialGroup()
                        .addGroup(Question0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(questionSetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );
        Question0Layout.setVerticalGroup(
            Question0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question0Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(questionSetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(answerProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Question0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Question0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNextMouseClicked
        // TODO add your handling code here:
        FormController.goNext(0);
    }//GEN-LAST:event_buttonNextMouseClicked

    private void answer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer1MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(0,"radio", evt.getSource());
        System.out.println("source is: " + evt.getSource().getClass());
    }//GEN-LAST:event_answer1MouseClicked

    private void answer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer2MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(0,"radio", evt.getSource());
    }//GEN-LAST:event_answer2MouseClicked

    private void answer3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer3MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(0,"radio", evt.getSource());
    }//GEN-LAST:event_answer3MouseClicked

    private void answer4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer4MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(0,"radio", evt.getSource());
    }//GEN-LAST:event_answer4MouseClicked

    private void answer5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer5MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(0,"radio", evt.getSource());
    }//GEN-LAST:event_answer5MouseClicked

    private void answer6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer6MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(0,"radio", evt.getSource());
    }//GEN-LAST:event_answer6MouseClicked

    private void answer7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer7MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(0,"radio", evt.getSource());
    }//GEN-LAST:event_answer7MouseClicked

    private void answer8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer8MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(0,"radio", evt.getSource());
    }//GEN-LAST:event_answer8MouseClicked
    
    @Override
    public void updateProgressBar(int progress) {
        answerProgressBar.setValue(progress);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Question0;
    private javax.swing.JRadioButton answer1;
    private javax.swing.JRadioButton answer2;
    private javax.swing.JRadioButton answer3;
    private javax.swing.JRadioButton answer4;
    private javax.swing.JRadioButton answer5;
    private javax.swing.JRadioButton answer6;
    private javax.swing.JRadioButton answer7;
    private javax.swing.JRadioButton answer8;
    private javax.swing.JProgressBar answerProgressBar;
    private javax.swing.JPanel answersPanel;
    private javax.swing.JButton buttonNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JPanel questionSetPanel;
    // End of variables declaration//GEN-END:variables
}
