/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swingkavir;

/**
 *
 * @author kaavi
 */
public class QuestionFrame1 extends javax.swing.JFrame implements QuestionInterface{

    /**
     * Creates new form QuestionFrame1
     */
    public QuestionFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Question1 = new javax.swing.JPanel();
        answerProgressBar = new javax.swing.JProgressBar();
        questionSetPanel3 = new javax.swing.JPanel();
        questionPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        answersPanel3 = new javax.swing.JPanel();
        answer1 = new java.awt.Button();
        answer2 = new java.awt.Button();
        buttonNext = new javax.swing.JButton();
        buttonPrevious = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 250));
        setResizable(false);

        Question1.setBackground(new java.awt.Color(108, 145, 191));
        Question1.setMaximumSize(new java.awt.Dimension(1000, 800));
        Question1.setMinimumSize(new java.awt.Dimension(1000, 800));

        questionSetPanel3.setBackground(new java.awt.Color(95, 154, 183));
        questionSetPanel3.setMaximumSize(new java.awt.Dimension(800, 500));
        questionSetPanel3.setMinimumSize(new java.awt.Dimension(800, 500));

        questionPanel3.setBackground(new java.awt.Color(95, 176, 183));
        questionPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Java is an OOP language");

        javax.swing.GroupLayout questionPanel3Layout = new javax.swing.GroupLayout(questionPanel3);
        questionPanel3.setLayout(questionPanel3Layout);
        questionPanel3Layout.setHorizontalGroup(
            questionPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        questionPanel3Layout.setVerticalGroup(
            questionPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        answersPanel3.setBackground(new java.awt.Color(95, 176, 183));
        answersPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        answer1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        answer1.setLabel("FALSE");
        answer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer1MouseClicked(evt);
            }
        });

        answer2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        answer2.setLabel("TRUE");
        answer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answer2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout answersPanel3Layout = new javax.swing.GroupLayout(answersPanel3);
        answersPanel3.setLayout(answersPanel3Layout);
        answersPanel3Layout.setHorizontalGroup(
            answersPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answersPanel3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        answersPanel3Layout.setVerticalGroup(
            answersPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answersPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(answersPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout questionSetPanel3Layout = new javax.swing.GroupLayout(questionSetPanel3);
        questionSetPanel3.setLayout(questionSetPanel3Layout);
        questionSetPanel3Layout.setHorizontalGroup(
            questionSetPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSetPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(questionSetPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(questionPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answersPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        questionSetPanel3Layout.setVerticalGroup(
            questionSetPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSetPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(questionPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(answersPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        buttonNext.setBackground(new java.awt.Color(95, 176, 183));
        buttonNext.setText("Next");
        buttonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNextMouseClicked(evt);
            }
        });

        buttonPrevious.setBackground(new java.awt.Color(95, 176, 183));
        buttonPrevious.setText("Previous");
        buttonPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPreviousMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(95, 154, 183));
        jLabel8.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Java Evaluation");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);

        javax.swing.GroupLayout Question1Layout = new javax.swing.GroupLayout(Question1);
        Question1.setLayout(Question1Layout);
        Question1Layout.setHorizontalGroup(
            Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(answerProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question1Layout.createSequentialGroup()
                        .addGroup(Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Question1Layout.createSequentialGroup()
                                .addComponent(buttonPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(questionSetPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );
        Question1Layout.setVerticalGroup(
            Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(questionSetPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonNext, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(buttonPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(answerProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNextMouseClicked
        // TODO add your handling code here:
        FormController.goNext(1);

    }//GEN-LAST:event_buttonNextMouseClicked

    private void buttonPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPreviousMouseClicked
        // TODO add your handling code here:
        FormController.goPrevious(1);
    }//GEN-LAST:event_buttonPreviousMouseClicked

    private void answer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer1MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(1,"bool", evt.getSource());

    }//GEN-LAST:event_answer1MouseClicked

    private void answer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answer2MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(1,"bool", evt.getSource());

    }//GEN-LAST:event_answer2MouseClicked

    @Override
    public void updateProgressBar(int progress) {
        answerProgressBar.setValue(progress);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Question1;
    private java.awt.Button answer1;
    private java.awt.Button answer2;
    private javax.swing.JProgressBar answerProgressBar;
    private javax.swing.JPanel answersPanel3;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonPrevious;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel questionPanel3;
    private javax.swing.JPanel questionSetPanel3;
    // End of variables declaration//GEN-END:variables
}
