/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swingkavir;

/**
 *
 * @author kaavi
 */
public class QuestionFrame7 extends javax.swing.JFrame implements QuestionInterface{

    /**
     * Creates new form QuestionFrame7
     */
    public QuestionFrame7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioAnswers3 = new javax.swing.ButtonGroup();
        Question7 = new javax.swing.JPanel();
        answerProgressBar = new javax.swing.JProgressBar();
        questionSetPanel2 = new javax.swing.JPanel();
        questionPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        answersPanel2 = new javax.swing.JPanel();
        radioAnswer2 = new javax.swing.JRadioButton();
        radioAnswer3 = new javax.swing.JRadioButton();
        radioAnswer4 = new javax.swing.JRadioButton();
        radioAnswer1 = new javax.swing.JRadioButton();
        radioAnswer5 = new javax.swing.JRadioButton();
        radioAnswer6 = new javax.swing.JRadioButton();
        radioAnswer7 = new javax.swing.JRadioButton();
        radioAnswer8 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 250));

        Question7.setBackground(new java.awt.Color(108, 145, 191));
        Question7.setMaximumSize(new java.awt.Dimension(1000, 800));
        Question7.setMinimumSize(new java.awt.Dimension(1000, 800));

        questionSetPanel2.setBackground(new java.awt.Color(95, 154, 183));
        questionSetPanel2.setMaximumSize(new java.awt.Dimension(800, 500));
        questionSetPanel2.setMinimumSize(new java.awt.Dimension(800, 500));

        questionPanel2.setBackground(new java.awt.Color(95, 176, 183));
        questionPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("What is (arguably) the best UI library for Java?");

        javax.swing.GroupLayout questionPanel2Layout = new javax.swing.GroupLayout(questionPanel2);
        questionPanel2.setLayout(questionPanel2Layout);
        questionPanel2Layout.setHorizontalGroup(
            questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        questionPanel2Layout.setVerticalGroup(
            questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        answersPanel2.setBackground(new java.awt.Color(95, 176, 183));
        answersPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        radioAnswers3.add(radioAnswer2);
        radioAnswer2.setText("SWT");
        radioAnswer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer2MouseClicked(evt);
            }
        });

        radioAnswers3.add(radioAnswer3);
        radioAnswer3.setText("JavaFX");
        radioAnswer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer3MouseClicked(evt);
            }
        });

        radioAnswers3.add(radioAnswer4);
        radioAnswer4.setText("CSS");
        radioAnswer4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer4MouseClicked(evt);
            }
        });

        radioAnswers3.add(radioAnswer1);
        radioAnswer1.setText("AWT");
        radioAnswer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer1MouseClicked(evt);
            }
        });

        radioAnswers3.add(radioAnswer5);
        radioAnswer5.setText("JavaUI");
        radioAnswer5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer5MouseClicked(evt);
            }
        });

        radioAnswers3.add(radioAnswer6);
        radioAnswer6.setText("Swing");
        radioAnswer6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer6MouseClicked(evt);
            }
        });

        radioAnswers3.add(radioAnswer7);
        radioAnswer7.setText("Vue");
        radioAnswer7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer7MouseClicked(evt);
            }
        });

        radioAnswers3.add(radioAnswer8);
        radioAnswer8.setText("React");
        radioAnswer8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioAnswer8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout answersPanel2Layout = new javax.swing.GroupLayout(answersPanel2);
        answersPanel2.setLayout(answersPanel2Layout);
        answersPanel2Layout.setHorizontalGroup(
            answersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answersPanel2Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addGroup(answersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answersPanel2Layout.createSequentialGroup()
                        .addComponent(radioAnswer1)
                        .addGap(44, 44, 44)
                        .addComponent(radioAnswer5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answersPanel2Layout.createSequentialGroup()
                        .addGroup(answersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioAnswer2)
                            .addComponent(radioAnswer3)
                            .addComponent(radioAnswer4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(answersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioAnswer8)
                            .addComponent(radioAnswer7)
                            .addComponent(radioAnswer6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        answersPanel2Layout.setVerticalGroup(
            answersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answersPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(answersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAnswer1)
                    .addComponent(radioAnswer5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(answersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioAnswer6)
                    .addComponent(radioAnswer2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(answersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAnswer3)
                    .addComponent(radioAnswer7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(answersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAnswer4)
                    .addComponent(radioAnswer8))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout questionSetPanel2Layout = new javax.swing.GroupLayout(questionSetPanel2);
        questionSetPanel2.setLayout(questionSetPanel2Layout);
        questionSetPanel2Layout.setHorizontalGroup(
            questionSetPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSetPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(questionSetPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(questionPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answersPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        questionSetPanel2Layout.setVerticalGroup(
            questionSetPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSetPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(questionPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(answersPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jButton5.setBackground(new java.awt.Color(95, 176, 183));
        jButton5.setText("Next");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(95, 176, 183));
        jButton6.setText("Previous");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(95, 154, 183));
        jLabel6.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Java Evaluation");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout Question7Layout = new javax.swing.GroupLayout(Question7);
        Question7.setLayout(Question7Layout);
        Question7Layout.setHorizontalGroup(
            Question7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(answerProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Question7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question7Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question7Layout.createSequentialGroup()
                        .addGroup(Question7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Question7Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(questionSetPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );
        Question7Layout.setVerticalGroup(
            Question7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(questionSetPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Question7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(answerProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Question7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Question7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        FormController.goPrevious(7);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        FormController.goNext(7);
    }//GEN-LAST:event_jButton5MouseClicked

    private void radioAnswer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer1MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(7,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer1MouseClicked

    private void radioAnswer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer2MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(7,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer2MouseClicked

    private void radioAnswer3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer3MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(7,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer3MouseClicked

    private void radioAnswer4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer4MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(7,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer4MouseClicked

    private void radioAnswer5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer5MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(7,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer5MouseClicked

    private void radioAnswer6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer6MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(7,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer6MouseClicked

    private void radioAnswer7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer7MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(7,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer7MouseClicked

    private void radioAnswer8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAnswer8MouseClicked
        // TODO add your handling code here:
        FormController.handleAnswer(7,"radio", evt.getSource());
    }//GEN-LAST:event_radioAnswer8MouseClicked

    @Override
    public void updateProgressBar(int progress) {
        answerProgressBar.setValue(progress);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Question7;
    private javax.swing.JProgressBar answerProgressBar;
    private javax.swing.JPanel answersPanel2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel questionPanel2;
    private javax.swing.JPanel questionSetPanel2;
    private javax.swing.JRadioButton radioAnswer1;
    private javax.swing.JRadioButton radioAnswer2;
    private javax.swing.JRadioButton radioAnswer3;
    private javax.swing.JRadioButton radioAnswer4;
    private javax.swing.JRadioButton radioAnswer5;
    private javax.swing.JRadioButton radioAnswer6;
    private javax.swing.JRadioButton radioAnswer7;
    private javax.swing.JRadioButton radioAnswer8;
    private javax.swing.ButtonGroup radioAnswers3;
    // End of variables declaration//GEN-END:variables
}
