/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swingkavir;

/**
 *
 * @author kaavi
 */
public class QuestionFrameEnd extends javax.swing.JFrame implements QuestionInterface{

    /**
     * Creates new form QuestionFrame9
     */
    public QuestionFrameEnd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Question9 = new javax.swing.JPanel();
        answerProgressBar = new javax.swing.JProgressBar();
        questionSetPanel9 = new javax.swing.JPanel();
        questionPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonFinish = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 250));
        setResizable(false);

        Question9.setBackground(new java.awt.Color(108, 145, 191));
        Question9.setMaximumSize(new java.awt.Dimension(1000, 800));
        Question9.setMinimumSize(new java.awt.Dimension(1000, 800));

        questionSetPanel9.setBackground(new java.awt.Color(95, 154, 183));
        questionSetPanel9.setMaximumSize(new java.awt.Dimension(800, 500));
        questionSetPanel9.setMinimumSize(new java.awt.Dimension(800, 500));

        questionPanel9.setBackground(new java.awt.Color(95, 176, 183));
        questionPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout questionPanel9Layout = new javax.swing.GroupLayout(questionPanel9);
        questionPanel9.setLayout(questionPanel9Layout);
        questionPanel9Layout.setHorizontalGroup(
            questionPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionPanel9Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        questionPanel9Layout.setVerticalGroup(
            questionPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel9Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout questionSetPanel9Layout = new javax.swing.GroupLayout(questionSetPanel9);
        questionSetPanel9.setLayout(questionSetPanel9Layout);
        questionSetPanel9Layout.setHorizontalGroup(
            questionSetPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSetPanel9Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(questionPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        questionSetPanel9Layout.setVerticalGroup(
            questionSetPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSetPanel9Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(questionPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        buttonFinish.setBackground(new java.awt.Color(95, 176, 183));
        buttonFinish.setText("Close");
        buttonFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFinishMouseClicked(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(95, 154, 183));
        jLabel20.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Java Evaluation");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel20.setOpaque(true);

        javax.swing.GroupLayout Question9Layout = new javax.swing.GroupLayout(Question9);
        Question9.setLayout(Question9Layout);
        Question9Layout.setHorizontalGroup(
            Question9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(answerProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Question9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(questionSetPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Question9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question9Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question9Layout.createSequentialGroup()
                        .addComponent(buttonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        Question9Layout.setVerticalGroup(
            Question9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Question9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(questionSetPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(answerProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1111, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Question9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Question9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFinishMouseClicked
        // TODO add your handling code here:
        FormController.finish();
    }//GEN-LAST:event_buttonFinishMouseClicked

    public void setLabelText(String finishText) {
        jLabel1.setText(finishText);
    }
    
    @Override
    public void updateProgressBar(int progress) {
        answerProgressBar.setValue(progress);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Question9;
    private javax.swing.JProgressBar answerProgressBar;
    private javax.swing.JButton buttonFinish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel questionPanel9;
    private javax.swing.JPanel questionSetPanel9;
    // End of variables declaration//GEN-END:variables
}
